@startuml

Title "Estrutura do arquivo do BU"

left to right direction

hide empty members

!define aenum       #fa9441
!define choice      #59b9de
!define sequence    #21c834
!define tipo        #c39deb
!define aenum_b     #fce2c5
!define choice_b    #c3ebfa
!define sequence_b  #b7f5bd
!define tipo_b      #ede3ff

class EntidadeBoletimUrna                   << (S, sequence) >>

package Envelope {
    class EntidadeEnvelopeGenerico              << (S, sequence) >>
    class TipoEnvelope                          << (E, aenum) >>
}

package Resultado {
    class CargoConstitucional                   << (E, aenum) >>
    class CodigoCargoConsulta                   << (C, choice) >>
    class IdentificacaoVotavel                  << (S, sequence) >>
    class ResultadoVotacao                      << (S, sequence) >>
    class ResultadoVotacaoPorEleicao            << (S, sequence) >>
    class TipoCargoConsulta                     << (E, aenum) >>
    class TipoVoto                              << (E, aenum) >>
    class TotalVotosCargo                       << (S, sequence) >>
    class TotalVotosVotavel                     << (S, sequence) >>
}

package Informacoes as "Informações auxiliares" {
    class ApuracaoEletronica                    << (S, sequence) >>
    class ApuracaoMistaBUAE                     << (S, sequence) >>
    class ApuracaoMistaMR                       << (S, sequence) >>
    class ApuracaoTotalmenteManualDigitacaoAE   << (S, sequence) >>
    class CabecalhoEntidade                     << (S, sequence) >>
    class Carga                                 << (S, sequence) >>
    class CorrespondenciaResultado              << (S, sequence) >>
    class DadosSA                               << (S, sequence) >>
    class DadosSecao                            << (S, sequence) >>
    class DadosSecaoSA                          << (C, choice) >>
    class Fase                                  << (E, aenum) >>
    class IDEleitoral                           << (C, choice) >>
    class IdentificacaoContingencia             << (S, sequence) >>
    class IdentificacaoSecaoEleitoral           << (S, sequence) >>
    class IdentificacaoUrna                     << (C, choice) >>
    class MotivoApuracaoEletronica              << (E, aenum) >>
    class MotivoApuracaoManual                  << (E, aenum) >>
    class MotivoApuracaoMistaComBU              << (E, aenum) >>
    class MotivoApuracaoMistaComMR              << (E, aenum) >>
    class MunicipioZona                         << (S, sequence) >>
    class TipoApuracao                          << (E, aenum) >>
    class TipoApuracaoSA                        << (C, choice) >>
    class TipoArquivo                           << (E, aenum) >>
    class TipoUrna                              << (E, aenum) >>
    class Urna                                  << (S, sequence) >>
    <> TipoApuracao_diamond
}

' Detalhes das entidades

class ApuracaoEletronica sequence_b {
    **tipoapuracao**
    **motivoApuracao**
}

class ApuracaoMistaBUAE sequence_b {
    **tipoapuracao**
    **motivoApuracao**
}

class ApuracaoMistaMR sequence_b {
    **tipoapuracao**
    **motivoApuracao**
}

class ApuracaoTotalmenteManualDigitacaoAE sequence_b {
    **tipoapuracao**
    **motivoApuracao**
}

class CabecalhoEntidade sequence_b {
    **dataGeracao** DataHoraJE
    **idEleitoral**
}

class Carga sequence_b {
    **numeroInternoUrna** NumeroInternoUrna
    **numeroSerieFC** NumeroSeriFlash
    **dataHoraCarga** DataHoraJE
    **codigoCarga** GeneralString
}

class CargoConstitucional aenum_b {
    **presidente** (1)
    --**vicePresidente**-- (2)
    **governador** (3)
    --**viceGovernador**-- (4)
    **senador** (5)
    **deputadoFederal** (6)
    **deputadoEstadual** (7)
    **deputadoDistrital** (8)
    --**primeiroSuplenteSenador**-- (9)
    --**segundoSuplenteSenador**-- (10)
    **prefeito** (11)
    --**vicePrefeito**-- (12)
    **vereador** (13)
}

class CodigoCargoConsulta choice_b {
    **cargoConstitucional**
    ..
    **numeroCargoConsultaLivre** NumeroCargoConsultaLivre
}

class CorrespondenciaResultado sequence_b {
    **identificacao**
    **carga**
}

class DadosSA sequence_b {
    **juntaApuradora** INTEGER
    **turmaApuradora** INTEGER
    **numeroInternoUrnaOrigem** NumeroInternoUrna OPTIONAL
}

class DadosSecao sequence_b {
    **dataHoraAbertura** DataHoraJE
    **dataHoraEncerramento** DataHoraJE
    **dataHoraDesligamentoVotoImpresso** DataHoraJE OPTIONAL
}

class DadosSecaoSA choice_b {
    **dadosSecao**
    ..
    **dadosSA**
}

class EntidadeBoletimUrna sequence_b {
    **cabecalho**
    **fase**
    **urna**
    **identificacaoSecao**
    **dataHoraEmissao** DataHoraJE
    **dadosSecaoSA**
    **qtdEleitoresLibCodigo** QtdEleitores OPTIONAL
    **qtdEleitoresCompBiometrico** QtdEleitores OPTIONAL
    **resultadosVotacaoPorEleicao**[]
    **historicoCorrespondencias**[] OPTIONAL,
    --**historicoVotoImpresso**--[] OPTIONAL,
    **chaveAssinaturaVotosVotavel** OCTET STRING
}

class EntidadeEnvelopeGenerico sequence_b {
    **cabecalho**
    **fase**
    **urna** OPTIONAL
    **identificacao**
    **tipoEnvelope**
    --**seguranca**-- OPTIONAL
    **conteudo** OCTET STRING
}

class Fase aenum_b {
    **simulado** (1)
    **oficial** (2)
    **treinamento** (3)
}

class IDEleitoral choice_b {
    **idProcessoEleitoral** IDProcessoEleitoral
    ..
    **idPleito** IDPleito
    ..
    **idEleicao** IDEleicao
}

class IdentificacaoContingencia sequence_b {
    **municipioZona**
}

class IdentificacaoSecaoEleitoral sequence_b {
    **municipioZona**
    **local** NumeroLocal
    **secao** NumeroSecao
}

class IdentificacaoUrna choice_b {
    **identificacaoSecaoEleitoral**
    ..
    **identificacaoContingencia**
}

class IdentificacaoVotavel sequence_b {
    **partido** NumeroPartido
    **codigo** NumeroVotavel
}

class MotivoApuracaoEletronica aenum_b {
    **naoFoiPossivelReuperarResultado** (1)
    **urnaNaoChegouMidiaDefeituosa** (2)
    **urnaNaoChegouMidiaExtraviada** (3)
    **outros** (99)
}

class MotivoApuracaoManual aenum_b {
   **urnaComDefeito** (1)
   **urnaIndisponivelInicio** (2)
   **urnaOutraSecao** (3)
   **outros** (99)
}

class MotivoApuracaoMistaComBU aenum_b {
    **urnaDataHoraIncorreta** (1)
    **urnaComDefeito** (2)
    **urnaOutrasecao** (3)
    **urnaPreparadaIncorretamente** (4)
    **urnaChegouAposInicioVotacao** (5)
    **outros**  (99)
}

class MotivoApuracaoMistaComMR aenum_b {
   **naoObteveExitoContingencia** (1)
   **indisponibilidadeUrnaContingencia** (2)
   **indisponibilidadeFlashContingencia** (3)
   **problemaEnergiaEletrica** (4)
   **naoFoiPossivelTrocarUrna** (5)
   **naoFoiSolicitadaTrocaUrna** (6)
   **outros** (99)
}

class MunicipioZona sequence_b {
    **municipio** CodigoMunicipio
    **zona** NumeroZona
}

class ResultadoVotacao sequence_b {
    **tipoCargo**
    **qtdComparecimento** QtdEleitores
    **totaisVotosCargo**[]
}

class ResultadoVotacaoPorEleicao sequence_b {
    **idEleicao** IDEleicao
    **qtdEleitoresAptos** QtdEleitores
    **resultadosVotacao**[]
}

class TipoApuracao aenum_b {
    **totalmenteManual** (1)
    **totalmenteEletronica** (2)
    **mistaBU** (3)
    **mistaMR** (4)
}

class TipoApuracaoSA choice_b {
    **apuracaoMistaMR**
    ..
    **apuracaoMistaBUAE**
    ..
    **apuracaoTotalmenteManual**
    ..
    **apuracaoEletronica**
}

class TipoArquivo aenum_b {
    **votacaoUE** (1)
    **votacaoRED** (2)
    **saMistaMRParcialCedula** (3)
    **saMistaBUImpressoCedula** (4)
    **saManual** (5)
    **saEletronica** (6)
}

class TipoCargoConsulta aenum_b {
    **majoritario** (1)
    **proporcional** (2)
    **consulta** (3)
}

class TipoEnvelope aenum_b {
    **envelopeBoletimUrna** (1)
    **envelopeRegistroDigitalVoto** (2)
    **envelopeBoletimUrnaImpresso** (4)
    **envelopeImagemBiometria** (5)
}

class TipoUrna aenum_b {
    **secao** (1)
    **contingencia** (3)
    **reservaSecao** (4)
    **reservaEncerrandoSecao** (6)
}

class TipoVoto aenum_b {
    **nominal** (1)
    **branco** (2)
    **nulo** (3)
    **legenda** (4)
    **cargoSemCandidato** (5)
}

class TotalVotosCargo sequence_b {
    **codigoCargo**
    **ordemImpressao** INTEGER [1..99]
    **votosVotaveis**
}

class TotalVotosVotavel sequence_b {
    **tipoVoto**
    **quantidadeVotos** QtdEleitores
    **identificacaoVotavel** OPTIONAL
    **assinatura** OCTET STRING
}

class Urna sequence_b {
    **tipoUrna**
    **versaoVotacao** GeneralString
    **correspondenciaResultado**
    **tipoArquivo**
    **numeroSerieFV** NumeroSerieFlash
    **motivoUtilizacaoSA** OPTIONAL
}

ApuracaoEletronica *--> MotivoApuracaoEletronica: motivoApuracao
ApuracaoEletronica *--> TipoApuracao_diamond
ApuracaoMistaBUAE *--> MotivoApuracaoMistaComBU: motivoApuracao
ApuracaoMistaBUAE *--> TipoApuracao_diamond
ApuracaoMistaMR *--> MotivoApuracaoMistaComMR: motivoApuracao
ApuracaoMistaMR *--> TipoApuracao_diamond
ApuracaoTotalmenteManualDigitacaoAE *--> MotivoApuracaoManual: motivoApuracao
ApuracaoTotalmenteManualDigitacaoAE *--> TipoApuracao_diamond
TipoApuracao_diamond --> TipoApuracao: tipoApuracao

CabecalhoEntidade *--> IDEleitoral: idEleitoral

CodigoCargoConsulta::cargoConstitucional --> CargoConstitucional

CorrespondenciaResultado *--> IdentificacaoUrna: identificacaoUrna
CorrespondenciaResultado *--> Carga: carga

DadosSecaoSA::dadosSecao --> DadosSecao: dadosSecao
DadosSecaoSA::dadosSA --> DadosSA: dadosSA

EntidadeBoletimUrna *--> CabecalhoEntidade: cabecalho
EntidadeBoletimUrna *--> Fase: fase
EntidadeBoletimUrna *--> Urna: urna
EntidadeBoletimUrna *--> IdentificacaoSecaoEleitoral: identificacaoSecao
EntidadeBoletimUrna *--> DadosSecaoSA: dadosSecaoSA
EntidadeBoletimUrna *-->"*" ResultadoVotacaoPorEleicao: resultadosVotacaoPorEleicao
EntidadeBoletimUrna o-->"*" CorrespondenciaResultado: historicoCorrespondencias

EntidadeEnvelopeGenerico *-left-> TipoEnvelope: tipoEnvelope
EntidadeEnvelopeGenerico ..> EntidadeBoletimUrna: conteudo
EntidadeEnvelopeGenerico *--> CabecalhoEntidade: cabecalho
EntidadeEnvelopeGenerico *--> Fase: fase
EntidadeEnvelopeGenerico o--> Urna: urna
EntidadeEnvelopeGenerico o--> IdentificacaoUrna: identificacao

IdentificacaoContingencia *--> MunicipioZona: municipioZona

IdentificacaoSecaoEleitoral *--> MunicipioZona: municipioZona

IdentificacaoUrna::identificacaoSecaoEleitoral --> IdentificacaoSecaoEleitoral
IdentificacaoUrna::identificacaoContingencia --> IdentificacaoContingencia

ResultadoVotacao *--> TipoCargoConsulta: tipoCargo
ResultadoVotacao *-->"*" TotalVotosCargo: totaisVotosCargo

ResultadoVotacaoPorEleicao *-->"*" ResultadoVotacao: resultadosVotacao

TotalVotosCargo *--> CodigoCargoConsulta: codigoCargo
TotalVotosCargo *-->"*" TotalVotosVotavel: votosVotaveis

TotalVotosVotavel *--> IdentificacaoVotavel: identificacaoVotavel
TotalVotosVotavel *--> TipoVoto: tipoVoto

Urna *--> TipoUrna: tipoUrna
Urna *--> CorrespondenciaResultado: correspondenciaResultado
Urna *--> TipoArquivo: tipoArquivo
Urna o--> TipoApuracaoSA: motivoUtilizacaoSA

TipoApuracaoSA::apuracaoEletronica --> ApuracaoEletronica
TipoApuracaoSA::apuracaoMistaBUAE --> ApuracaoMistaBUAE
TipoApuracaoSA::apuracaoMistaMR --> ApuracaoMistaMR
TipoApuracaoSA::apuracaoTotalmenteManual --> ApuracaoTotalmenteManualDigitacaoAE

@enduml
